CREATE OR REPLACE PROCEDURE I2B2DEMODATA.CREATE_TEMP_PID_TABLE(CHARACTER VARYING(ANY))
RETURNS CHARACTER VARYING(ANY)
LANGUAGE NZPLSQL AS
BEGIN_PROC
DECLARE
	tempPatientMappingTableName ALIAS FOR $1;
	
BEGIN

execute IMMEDIATE 'create table ' ||  tempPatientMappingTableName || ' (
	   	PATIENT_MAP_ID VARCHAR(200), 
		PATIENT_MAP_ID_SOURCE VARCHAR(50), 
		PATIENT_ID_STATUS VARCHAR(50), 
		PATIENT_ID  VARCHAR(200),
	    PATIENT_ID_SOURCE VARCHAR(50),
		PATIENT_NUM NUMERIC(38,0),
	    PATIENT_MAP_ID_STATUS VARCHAR(50), 
		PROCESS_STATUS_FLAG CHAR(1), 
		UPDATE_DATE TIMESTAMP, 
		DOWNLOAD_DATE TIMESTAMP, 
		IMPORT_DATE TIMESTAMP, 
		SOURCESYSTEM_CD VARCHAR(50)

	 )';
	 

return 'table created' ;

EXCEPTION
	WHEN OTHERS THEN
		RAISE NOTICE 'Exception Raised: %', SQLERRM;
END;
END_PROC;