CREATE OR REPLACE PROCEDURE I2B2DEMODATA.CREATE_TEMP_PROVIDER_TABLE(CHARACTER VARYING(ANY))
RETURNS CHARACTER VARYING(ANY)

LANGUAGE NZPLSQL AS
BEGIN_PROC
DECLARE
	tempProviderTableName ALIAS FOR $1;
	
BEGIN
execute IMMEDIATE 'create table ' ||  tempProviderTableName || ' (
    PROVIDER_ID VARCHAR(50) NOT NULL, 
	PROVIDER_PATH VARCHAR(700) NOT NULL, 
	NAME_CHAR VARCHAR(2000), 
	PROVIDER_BLOB varchar(60000), 
	UPDATE_DATE TIMESTAMP, 
	DOWNLOAD_DATE TIMESTAMP, 
	IMPORT_DATE TIMESTAMP, 
	SOURCESYSTEM_CD VARCHAR(50), 
	UPLOAD_ID NUMERIC(38,0)
	 )';
	 

return 'table created' ;

EXCEPTION
	WHEN OTHERS THEN
		RAISE NOTICE 'Exception Raised: %', SQLERRM;
END;
END_PROC;


