CREATE OR REPLACE PROCEDURE I2B2DEMODATA.REMOVE_TEMP_TABLE(CHARACTER VARYING(ANY))
RETURNS  CHARACTER VARYING(ANY)

LANGUAGE NZPLSQL AS
BEGIN_PROC
DECLARE
	tempTableName ALIAS FOR $1;
BEGIN

	execute IMMEDIATE  'drop table ' || tempTableName ;

return 'Table dropped' ;

EXCEPTION
	WHEN OTHERS THEN
		RAISE NOTICE 'Exception Raised: %', SQLERRM;
END;
END_PROC;